# Generated by Django 5.2.12 on 2026-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('midi_file', models.FileField(null=True, upload_to='midi/')),
                ('musicxml_file', models.FileField(null=True, upload_to='xml/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bpm', models.FloatField(null=True)),
                ('key_signature', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
