# Generated by Django 5.2.12 on 2026-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='key_signature',
        ),
        migrations.AddField(
            model_name='transcription',
            name='note_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
