# Generated by Django 5.2.12 on 2026-03-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_remove_transcription_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='time_signature',
            field=models.CharField(default='4/4', max_length=10),
        ),
    ]
